### ISSUE TITLE
Application crashes with Python2.7.15

### ISSUE THREAD

**Issue by andrewlik7** [Critical-Start/FallofSudo#6]
Application crashes with Python2.7.15.
```
Author: paragonsec @ Critical Start (https://www.criticalstart.com)
Contributor: rmirch
Version: 1.1
Description: This program aids pentesters in conducting privilege escalation on Linux by abusing sudo. Use for good or training purposes ONLY!

[+] Obtaining sudo rules for user root

[!] root has the following sudo rules:

[+] Identifying potential pwnage... 


[?] Enter name of sudo rule you wish to pwn: all
Traceback (most recent call last):
  File "./fallofsudo.py", line 1783, in <module>
    main()
  File "./fallofsudo.py", line 81, in main
    sudopwner()
  File "./fallofsudo.py", line 249, in sudopwner
    all(all_user)
UnboundLocalError: local variable 'all_user' referenced before assignment
```

**Comment by paragonsec** [comment]
I am not seeing that same issue when using 2.7.15rc1. In your above output I am not seeing the program return the list of rules from Output/sudorules.txt which should have been generated python the output of sudo -ll command. Can you see that file being created?
```
paragonsec@paragonsec:~$ python -V
Python 2.7.15rc1
paragonsec@paragonsec:~$ python fallofsudo.py -i

  █████▒▄▄▄       ██▓     ██▓        ▒█████    █████▒     ██████  █    ██ ▓█████▄  ▒█████
▓██   ▒▒████▄    ▓██▒    ▓██▒       ▒██▒  ██▒▓██   ▒    ▒██    ▒  ██  ▓██▒▒██▀ ██▌▒██▒  ██▒
▒████ ░▒██  ▀█▄  ▒██░    ▒██░       ▒██░  ██▒▒████ ░    ░ ▓██▄   ▓██  ▒██░░██   █▌▒██░  ██▒
░▓█▒  ░░██▄▄▄▄██ ▒██░    ▒██░       ▒██   ██░░▓█▒  ░      ▒   ██▒▓▓█  ░██░░▓█▄   ▌▒██   ██░
░▒█░    ▓█   ▓██▒░██████▒░██████▒   ░ ████▓▒░░▒█░       ▒██████▒▒▒▒█████▓ ░▒████▓ ░ ████▓▒░
 ▒ ░    ▒▒   ▓▒█░░ ▒░▓  ░░ ▒░▓  ░   ░ ▒░▒░▒░  ▒ ░       ▒ ▒▓▒ ▒ ░░▒▓▒ ▒ ▒  ▒▒▓  ▒ ░ ▒░▒░▒░
 ░       ▒   ▒▒ ░░ ░ ▒  ░░ ░ ▒  ░     ░ ▒ ▒░  ░         ░ ░▒  ░ ░░░▒░ ░ ░  ░ ▒  ▒   ░ ▒ ▒░
 ░ ░     ░   ▒     ░ ░     ░ ░      ░ ░ ░ ▒   ░ ░       ░  ░  ░   ░░░ ░ ░  ░ ░  ░ ░ ░ ░ ▒
             ░  ░    ░  ░    ░  ░       ░ ░                   ░     ░        ░        ░ ░
                                                                           ░

Author: paragonsec @ Critical Start (https://www.criticalstart.com)
Contributor: rmirch
Version: 1.1
Description: This program aids pentesters in conducting privilege escalation on Linux by abusing sudo. Use for good or training purposes ONLY!

[+] Obtaining sudo rules for user paragonsec

[!] paragonsec has the following sudo rules:

[!] RunAsUsers: ALL
[!] RunAsGroups: ALL
[!] Commands: ALL

[+] Identifying potential pwnage...

[!] Vulnerable sudo rule [EASY TO PWN]: all

[?] Enter name of sudo rule you wish to pwn: all

-----------------------------------------------------------------------------------------------------------------------------

[!] HOW TO PWN THIS RULE!!!
[+] To pwn this rule type one of the two commands:
[*] sudo -i
[*] sudo su

-----------------------------------------------------------------------------------------------------------------------------
```
